// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: %eopt --enzyme --canonicalize --remove-unnecessary-enzyme-ops --canonicalize %s | FileCheck %s

// Flattened output of clang -fclangir -emit-cir -O1 -fno-math-errno for
//   #include <math.h>
//   double poly(double x, double y) { double t = x * y + 2.0; return sin(t) / x; }

!s32i = !cir.int<s, 32>
module {
  cir.func @poly(%arg0: !cir.double, %arg1: !cir.double) -> !cir.double {
    %0 = cir.const #cir.int<1> : !s32i
    %1 = cir.const #cir.fp<2.000000e+00> : !cir.double
    %2 = cir.alloca "__cleanup_dest_slot" align(4) cleanup_dest_slot : !cir.ptr<!s32i>
    %3 = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
    %4 = cir.alloca "y" align(8) init : !cir.ptr<!cir.double>
    %5 = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
    %6 = cir.alloca "t" align(8) init : !cir.ptr<!cir.double>
    cir.store %arg0, %3 : !cir.double, !cir.ptr<!cir.double>
    cir.store %arg1, %4 : !cir.double, !cir.ptr<!cir.double>
    cir.lifetime.start %6 : !cir.ptr<!cir.double>
    %7 = cir.load align(8) %3 : !cir.ptr<!cir.double>, !cir.double
    %8 = cir.load align(8) %4 : !cir.ptr<!cir.double>, !cir.double
    %9 = cir.fmuladd %7, %8, %1 : !cir.double
    cir.store align(8) %9, %6 : !cir.double, !cir.ptr<!cir.double>
    %10 = cir.load align(8) %6 : !cir.ptr<!cir.double>, !cir.double
    %11 = cir.sin %10 : !cir.double
    %12 = cir.load align(8) %3 : !cir.ptr<!cir.double>, !cir.double
    %13 = cir.fdiv %11, %12 : !cir.double
    cir.store %13, %5 : !cir.double, !cir.ptr<!cir.double>
    cir.store %0, %2 : !s32i, !cir.ptr<!s32i>
    cir.lifetime.end %6 : !cir.ptr<!cir.double>
    %14 = cir.load %2 : !cir.ptr<!s32i>, !s32i
    cir.switch.flat %14 : !s32i, ^bb3 [
      0: ^bb1,
      1: ^bb2
    ]
  ^bb1:
    %15 = cir.load %5 : !cir.ptr<!cir.double>, !cir.double
    cir.return %15 : !cir.double
  ^bb2:
    %16 = cir.load %5 : !cir.ptr<!cir.double>, !cir.double
    cir.return %16 : !cir.double
  ^bb3:
    cir.unreachable
  }
  cir.func @fwd(%x: !cir.double, %dx: !cir.double, %y: !cir.double, %dy: !cir.double) -> !cir.double {
    %r = enzyme.fwddiff @poly(%x, %dx, %y, %dy) { activity=[#enzyme.activity<enzyme_dup>, #enzyme.activity<enzyme_dup>], ret_activity=[#enzyme.activity<enzyme_dupnoneed>] } : (!cir.double, !cir.double, !cir.double, !cir.double) -> !cir.double
    cir.return %r : !cir.double
  }
}

// CHECK-LABEL:   cir.func private @fwddiffepoly(
// CHECK-SAME:      %[[ARG0:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG1:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG2:[a-zA-Z0-9$._-]+]]: !cir.double,
// CHECK-SAME:      %[[ARG3:[a-zA-Z0-9$._-]+]]: !cir.double) -> !cir.double {
// CHECK:           %[[CONST_0:.*]] = cir.const #cir.int<0> : !s32i
// CHECK:           %[[CONST_1:.*]] = cir.const #cir.int<1> : !s32i
// CHECK:           %[[CONST_2:.*]] = cir.const #cir.fp<2.000000e+00> : !cir.double
// CHECK:           %[[ALLOCA_0:.*]] = cir.alloca "__cleanup_dest_slot" align(4) cleanup_dest_slot : !cir.ptr<!s32i>
// CHECK:           %[[ALLOCA_1:.*]] = cir.alloca "__cleanup_dest_slot" align(4) cleanup_dest_slot : !cir.ptr<!s32i>
// CHECK:           %[[ALLOCA_2:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_3:.*]] = cir.alloca "x" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_4:.*]] = cir.alloca "y" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_5:.*]] = cir.alloca "y" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_6:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_7:.*]] = cir.alloca "__retval" align(8) : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_8:.*]] = cir.alloca "t" align(8) init : !cir.ptr<!cir.double>
// CHECK:           %[[ALLOCA_9:.*]] = cir.alloca "t" align(8) init : !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG1]], %[[ALLOCA_2]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG0]], %[[ALLOCA_3]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG3]], %[[ALLOCA_4]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[ARG2]], %[[ALLOCA_5]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.lifetime.start %[[ALLOCA_8]] : !cir.ptr<!cir.double>
// CHECK:           cir.lifetime.start %[[ALLOCA_9]] : !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_0:.*]] = cir.load align(8) %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_1:.*]] = cir.load align(8) %[[ALLOCA_3]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_2:.*]] = cir.load align(8) %[[ALLOCA_4]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_3:.*]] = cir.load align(8) %[[ALLOCA_5]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_0:.*]] = cir.fmul %[[LOAD_0]], %[[LOAD_3]] : !cir.double
// CHECK:           %[[FMUL_1:.*]] = cir.fmul %[[LOAD_2]], %[[LOAD_1]] : !cir.double
// CHECK:           %[[FADD_0:.*]] = cir.fadd %[[FMUL_0]], %[[FMUL_1]] : !cir.double
// CHECK:           %[[FMULADD_0:.*]] = cir.fmuladd %[[LOAD_1]], %[[LOAD_3]], %[[CONST_2]] : !cir.double
// CHECK:           cir.store align(8) %[[FADD_0]], %[[ALLOCA_8]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store align(8) %[[FMULADD_0]], %[[ALLOCA_9]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_4:.*]] = cir.load align(8) %[[ALLOCA_8]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_5:.*]] = cir.load align(8) %[[ALLOCA_9]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[COS_0:.*]] = cir.cos %[[LOAD_5]] : !cir.double
// CHECK:           %[[FMUL_2:.*]] = cir.fmul %[[LOAD_4]], %[[COS_0]] : !cir.double
// CHECK:           %[[SIN_0:.*]] = cir.sin %[[LOAD_5]] : !cir.double
// CHECK:           %[[LOAD_6:.*]] = cir.load align(8) %[[ALLOCA_2]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[LOAD_7:.*]] = cir.load align(8) %[[ALLOCA_3]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           %[[FMUL_3:.*]] = cir.fmul %[[FMUL_2]], %[[LOAD_7]] : !cir.double
// CHECK:           %[[FMUL_4:.*]] = cir.fmul %[[LOAD_6]], %[[SIN_0]] : !cir.double
// CHECK:           %[[FSUB_0:.*]] = cir.fsub %[[FMUL_3]], %[[FMUL_4]] : !cir.double
// CHECK:           %[[FMUL_5:.*]] = cir.fmul %[[LOAD_7]], %[[LOAD_7]] : !cir.double
// CHECK:           %[[FDIV_0:.*]] = cir.fdiv %[[FSUB_0]], %[[FMUL_5]] : !cir.double
// CHECK:           %[[FDIV_1:.*]] = cir.fdiv %[[SIN_0]], %[[LOAD_7]] : !cir.double
// CHECK:           cir.store %[[FDIV_0]], %[[ALLOCA_6]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[FDIV_1]], %[[ALLOCA_7]] : !cir.double, !cir.ptr<!cir.double>
// CHECK:           cir.store %[[CONST_0]], %[[ALLOCA_0]] : !s32i, !cir.ptr<!s32i>
// CHECK:           cir.store %[[CONST_1]], %[[ALLOCA_1]] : !s32i, !cir.ptr<!s32i>
// CHECK:           cir.lifetime.end %[[ALLOCA_8]] : !cir.ptr<!cir.double>
// CHECK:           cir.lifetime.end %[[ALLOCA_9]] : !cir.ptr<!cir.double>
// CHECK:           %[[LOAD_8:.*]] = cir.load %[[ALLOCA_1]] : !cir.ptr<!s32i>, !s32i
// CHECK:           cir.switch.flat %[[LOAD_8]] : !s32i, ^bb3 [
// CHECK:             0: ^bb1,
// CHECK:             1: ^bb2
// CHECK:           ]
// CHECK:         ^bb1:
// CHECK:           %[[LOAD_9:.*]] = cir.load %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_9]] : !cir.double
// CHECK:         ^bb2:
// CHECK:           %[[LOAD_10:.*]] = cir.load %[[ALLOCA_6]] : !cir.ptr<!cir.double>, !cir.double
// CHECK:           cir.return %[[LOAD_10]] : !cir.double
// CHECK:         ^bb3:
// CHECK:           cir.unreachable
// CHECK:         }
